// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDMUDTn4y-eRbqjY-4H4DR-ay8b6oOhg',
    appId: '1:470589391861:web:d2a27ff5451f65b47b56bc',
    messagingSenderId: '470589391861',
    projectId: 'basirah-tv',
    authDomain: 'basirah-tv.firebaseapp.com',
    storageBucket: 'basirah-tv.firebasestorage.app',
    measurementId: 'G-13FQFMZJST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB092EF6hvm5tuM_Pmtu3veFX1tFxRL_9w',
    appId: '1:470589391861:android:391d39cc904199357b56bc',
    messagingSenderId: '470589391861',
    projectId: 'basirah-tv',
    storageBucket: 'basirah-tv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPAC0xysZsWbFEru4dwX83XP2SLURYVl4',
    appId: '1:470589391861:ios:823ea12be40290267b56bc',
    messagingSenderId: '470589391861',
    projectId: 'basirah-tv',
    storageBucket: 'basirah-tv.firebasestorage.app',
    iosBundleId: 'com.yourdomain.basirah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPAC0xysZsWbFEru4dwX83XP2SLURYVl4',
    appId: '1:470589391861:ios:81dd6b20be17e7537b56bc',
    messagingSenderId: '470589391861',
    projectId: 'basirah-tv',
    storageBucket: 'basirah-tv.firebasestorage.app',
    iosBundleId: 'com.example.bayyinahClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSDMUDTn4y-eRbqjY-4H4DR-ay8b6oOhg',
    appId: '1:470589391861:web:020d5d61d4dfd1707b56bc',
    messagingSenderId: '470589391861',
    projectId: 'basirah-tv',
    authDomain: 'basirah-tv.firebaseapp.com',
    storageBucket: 'basirah-tv.firebasestorage.app',
    measurementId: 'G-NDKN30Z4EE',
  );

}